spring:
  application:
    name: url-shortener
  threads:
    virtual:
      enabled: true
  config:
      import: "optional:configserver:http://localhost:8888"
app:
  instance:
    id: ${INSTANCE_ID:0}

server:
    port: 8081