spring:
  application:
    name: Url Shortener Service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
  threads:
    virtual:
      enabled: true
app:
  instance:
    id: ${INSTANCE_ID:0}
