spring.application.name=redirect-service

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=password

spring.config.import=optional:configserver:http://localhost:8888

server.port=8081